#pragma once
std::string getHWinfo64();
std::string getProductId();
std::string getCurrentBuild();
std::string getMachineId();
char* getMAC();
char* getVolumeId();
std::string GetProcessorId();
std::string GetBaseboard();